---
apiVersion: v1
kind: ConfigMap
metadata:
  name: kubewatch
data:
  .kubewatch.yaml: |
    namespace: ""
    handler:
      slack:
        token: <token>
        channel: <channel>
    resource:
      deployment: false
      replicationcontroller: false
      replicaset: false
      daemonset: false
      services: true
      pod: true
      secret: false
      configmap: false
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: kubewatch
rules:
- apiGroups: [""]
  resources: ["events"]
  verbs: ["get", "watch", "list"]
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: kubewatch
  namespace: default
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: kubewatch
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: kubewatch
subjects:
  - kind: ServiceAccount
    name: kubewatch
    namespace: default
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kubewatch-deployment
spec:
  selector:
    matchLabels:
      app: kubewatch
  replicas: 1
  template:
    metadata:
      labels:
        app: kubewatch
    spec:
      serviceAccountName: kubewatch
      containers:
      - image: artifactory.robinsystems.com/docker/bitnami/kubewatch:1.0
        imagePullPolicy: Always
        name: kubewatch
        volumeMounts:
        - name: config-volume
          mountPath: /root
      restartPolicy: Always
      volumes:
      - name: config-volume
        configMap:
          name: kubewatch